import * as THREE from 'three';
import { PointerLockControls } from 'three/addons/controls/PointerLockControls.js';

const root=document.getElementById('game'),clockEl=document.getElementById('clock'),objectiveEl=document.getElementById('objective'),hintEl=document.getElementById('hint'),interactionEl=document.getElementById('interaction'),startEl=document.getElementById('start');
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x07101b); scene.fog=new THREE.FogExp2(0x07101b,.018);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,220); camera.position.set(0,1.65,8.7);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setSize(innerWidth,innerHeight); renderer.setPixelRatio(Math.min(devicePixelRatio,1.8)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.05; root.appendChild(renderer.domElement);
const controls=new PointerLockControls(camera,renderer.domElement),keys=new Set(),clock=new THREE.Clock(); let elapsed=0,gameMinutes=19*60,trainIndex=0,train=null,signalClear=false,dinnerPacked=false,doorOpen=false,lampTime=0;
const trainSchedule=[19*60+30,20*60+30,21*60+15,22*60],colliders=[],interactables=[],worldPos=new THREE.Vector3();
const mat=(color,roughness=.8,metalness=0)=>new THREE.MeshStandardMaterial({color,roughness,metalness});
const M={plaster:mat(0x6f655b,.95),wood:mat(0x4a2e1f,.9),woodLight:mat(0x775039,.9),floor:mat(0x302820,1),roof:mat(0x202327,.98),metal:mat(0x3e454a,.45,.7),rail:mat(0x4b4f52,.28,.9),sleeper:mat(0x3d2b20,.95),gravel:mat(0x4a4742,1),glass:new THREE.MeshStandardMaterial({color:0x71899a,roughness:.12,transparent:true,opacity:.28}),red:mat(0x9b2d28,.5),green:mat(0x3e8b59,.45),black:mat(0x17191b,.95),cloth:mat(0x66594f,1),foliage:mat(0x183026,1)};
function addCollider(mesh,size){colliders.push({mesh,size:new THREE.Vector3(...size)});}
function box(name,size,pos,material,parent=scene,collision=false){const m=new THREE.Mesh(new THREE.BoxGeometry(...size),material);m.name=name;m.position.set(...pos);m.castShadow=true;m.receiveShadow=true;parent.add(m);if(collision)addCollider(m,size);return m;}
function cylinder(name,radius,height,pos,material,parent=scene,segments=16,collision=false){const m=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,height,segments),material);m.name=name;m.position.set(...pos);m.castShadow=true;m.receiveShadow=true;parent.add(m);if(collision)addCollider(m,[radius*2,height,radius*2]);return m;}
function addInteractable(mesh,label,action,range=2.2){mesh.userData.interact={label,action,range};interactables.push(mesh);return mesh;}
function collidesAt(pos){const r=.32,b=.1,t=1.65,minPX=pos.x-r,maxPX=pos.x+r,minPZ=pos.z-r,maxPZ=pos.z+r;for(const c of colliders){c.mesh.getWorldPosition(worldPos);const s=c.size,p=worldPos,minX=p.x-s.x/2,maxX=p.x+s.x/2,minZ=p.z-s.z/2,maxZ=p.z+s.z/2,minY=p.y-s.y/2,maxY=p.y+s.y/2;if(maxY<=b+.02)continue;if(minY>=t)continue;if(maxPX>minX&&minPX<maxX&&maxPZ>minZ&&minPZ<maxZ)return true;}return false;}
function movePlayer(dx,dz){const x=camera.position.clone();x.x+=dx;if(!collidesAt(x))camera.position.x=x.x;const z=camera.position.clone();z.z+=dz;if(!collidesAt(z))camera.position.z=z.z;camera.position.x=THREE.MathUtils.clamp(camera.position.x,-17,17);camera.position.z=THREE.MathUtils.clamp(camera.position.z,-52,10.8);camera.position.y=1.65;}
scene.add(new THREE.HemisphereLight(0x8da9d4,0x18130f,.78));const moon=new THREE.DirectionalLight(0xb7c9ff,1.8);moon.position.set(-28,35,18);moon.castShadow=true;moon.shadow.mapSize.set(2048,2048);moon.shadow.camera.left=-70;moon.shadow.camera.right=70;moon.shadow.camera.top=70;moon.shadow.camera.bottom=-70;scene.add(moon);const md=new THREE.Mesh(new THREE.SphereGeometry(2.2,24,24),new THREE.MeshBasicMaterial({color:0xdde8ff}));md.position.set(-42,34,-70);scene.add(md);
const sg=new THREE.BufferGeometry(),sp=[];for(let i=0;i<260;i++){const a=Math.random()*Math.PI*2,r=70+Math.random()*50;sp.push(Math.cos(a)*r,18+Math.random()*45,-20-Math.random()*90);}sg.setAttribute('position',new THREE.Float32BufferAttribute(sp,3));scene.add(new THREE.Points(sg,new THREE.PointsMaterial({color:0xc9d8ee,size:.12,sizeAttenuation:true})));
box('ground',[70,.25,140],[0,-.18,-38],M.gravel);box('yard',[38,.03,100],[0,-.02,-38],mat(0x3c3935,1));
const cabin=new THREE.Group();scene.add(cabin);box('floor',[12,.35,9],[0,0,8],M.floor,cabin);box('back wall',[12,4.6,.32],[0,2.3,12.34],M.plaster,cabin,true);box('left wall',[.32,4.6,9],[-5.84,2.3,8],M.plaster,cabin,true);box('right wall',[.32,4.6,9],[5.84,2.3,8],M.plaster,cabin,true);box('front left',[4.1,4.6,.32],[-3.95,2.3,3.66],M.plaster,cabin,true);box('front right',[4.1,4.6,.32],[3.95,2.3,3.66],M.plaster,cabin,true);box('lintel',[3.8,1.1,.32],[0,4.05,3.66],M.plaster,cabin,true);box('roof',[13,.42,10],[0,4.72,8],M.roof,cabin);
const doorPivot=new THREE.Object3D();doorPivot.position.set(-1.1,0,3.48);scene.add(doorPivot);const door=box('door',[2.2,3.85,.18],[1.1,1.93,0],M.woodLight,doorPivot);const doorCollider={mesh:door,size:new THREE.Vector3(2.2,3.85,.18)};colliders.push(doorCollider);addInteractable(door,'Open door',()=>{doorOpen=!doorOpen;doorPivot.userData.target=doorOpen?-Math.PI/2:0;if(doorOpen){const i=colliders.indexOf(doorCollider);if(i>=0)colliders.splice(i,1);door.userData.interact.label='Close door';}else{if(!colliders.includes(doorCollider))colliders.push(doorCollider);door.userData.interact.label='Open door';}});
function windowFrame(x,y,z,ry=0){const g=new THREE.Group();g.position.set(x,y,z);g.rotation.y=ry;scene.add(g);box('window top',[3.2,.18,.18],[0,.9,0],M.wood,g);box('window bottom',[3.2,.18,.18],[0,-.9,0],M.wood,g);box('window left',[.18,1.8,.18],[-1.5,0,0],M.wood,g);box('window right',[.18,1.8,.18],[1.5,0,0],M.wood,g);box('glass',[2.8,1.45,.05],[0,0,-.02],M.glass,g);}windowFrame(-5.65,2.65,8,Math.PI/2);
box('desk',[3.4,.28,1.1],[-1.8,1.35,9.8],M.woodLight,cabin,true);for(const x of[-3.15,-.45])box('desk leg',[.22,1.35,.22],[x,.67,9.8],M.wood,cabin,true);box('chair',[1.1,.22,1],[1.4,.8,9.5],M.woodLight,cabin,true);box('bed',[2.7,.5,4],[3.5,.38,6.8],M.wood,cabin,true);box('mattress',[2.45,.18,3.7],[3.5,.72,6.8],M.cloth,cabin);const stove=box('stove',[1.35,1,1],[-3.8,.65,6],M.metal,cabin,true);addInteractable(stove,'Cook dinner',()=>{if(!train){dinnerPacked=true;objectiveEl.textContent='Dinner packed. Return to the signal cabin desk.';}});
const lantern=new THREE.PointLight(0xffb86c,4.2,10,2);lantern.position.set(-1.4,3,9);lantern.castShadow=true;scene.add(lantern);const signalBox=box('signal control',[.9,1.2,.8],[0,.6,5.4],M.metal,scene,true);const leverPivot=new THREE.Object3D();leverPivot.position.set(.25,.9,5);scene.add(leverPivot);box('lever stem',[.12,1.45,.12],[0,.7,0],M.metal,leverPivot);box('lever handle',[.9,.12,.12],[.3,1.28,0],M.red,leverPivot);
for(const x of[-1.25,1.25])box('rail',[.16,.12,120],[x,.1,-55],M.rail);for(let z=2;z>=-112;z-=2.2)box('sleeper',[3.5,.14,.25],[0,.02,z],M.sleeper);box('ballast',[4.2,.16,120],[0,-.02,-55],M.gravel);
const signal=new THREE.Group();signal.position.set(3.7,0,1);scene.add(signal);cylinder('signal pole',.11,5.2,[0,2.6,0],M.metal,signal);box('signal housing',[.9,1.5,.5],[0,4.35,0],M.black,signal);const signalLamp=new THREE.PointLight(0xa72b2b,2.8,9);signalLamp.position.set(0,4.35,-.3);signal.add(signalLamp);const signalDisc=cylinder('signal lamp',.28,.08,[0,4.35,-.31],M.red,signal,16);signalDisc.rotation.x=Math.PI/2;
const barrierPivot=new THREE.Object3D();barrierPivot.position.set(5,1,2.2);scene.add(barrierPivot);box('barrier',[.16,.16,10],[-5,0,0],M.woodLight,barrierPivot);for(let x=-9.2;x<=-.8;x+=.8)box('stripe',[.38,.18,.18],[x,.02,0],M.red,barrierPivot);
const streetPole=cylinder('street pole',.11,5.8,[8.2,2.9,3],M.metal);const streetLamp=new THREE.PointLight(0xffc98f,5.5,16,2);streetLamp.position.set(8.2,5.8,3);streetLamp.castShadow=true;scene.add(streetLamp);cylinder('lamp head',.27,.18,[8.2,5.9,3],M.black);
function addTree(x,z,s=1){cylinder('trunk',.25*s,2.4*s,[x,1.2*s,z],M.wood);for(let i=0;i<3;i++){const c=new THREE.Mesh(new THREE.IcosahedronGeometry(1*s,0),M.foliage);c.position.set(x+(i-1)*.45*s,2.4*s+i*.45*s,z+(i%2)*.35*s);c.castShadow=true;scene.add(c);}}[[-11,2,1.5],[12,0,1.6],[-13,-13,1.8],[13,-20,1.8],[-11,-29,1.5],[11,-37,1.6],[-15,-48,1.8],[15,-52,1.8]].forEach(v=>addTree(...v));
function addTrain(){const group=new THREE.Group();group.position.set(0,1.6,-105);scene.add(group);const body=mat(0x3e4852,.42,.45),dark=mat(0x1a2730,.3,.25);for(let i=0;i<6;i++){const z=i*7.6;box(`coach-${i}`,[5.4,3.1,7.1],[0,0,z],body,group);box(`windows-${i}`,[5.45,1,.12],[0,.55,z-3.1],dark,group);}const head=new THREE.PointLight(0xffefc4,11,42,2);head.position.set(0,0,-4);group.add(head);train={group,speed:25};objectiveEl.textContent='TRAIN APPROACHING — operate the signal.';}
function toggleSignal(){signalClear=!signalClear;signalDisc.material=signalClear?M.green:M.red;signalLamp.color.setHex(signalClear?0x55ff91:0xb52c2c);leverPivot.rotation.z=signalClear?-.7:0;barrierPivot.userData.target=signalClear?-Math.PI/2:0;objectiveEl.textContent=signalClear?'Signal clear. Wait for the train.':'Signal red. Operate it when the train is due.';}addInteractable(signalBox,'Operate signal',toggleSignal,2.5);
function nearestInteractable(){let best=null,bd=Infinity,forward=new THREE.Vector3();camera.getWorldDirection(forward);for(const mesh of interactables){if(!mesh.visible||!mesh.userData.interact)continue;const w=mesh.getWorldPosition(new THREE.Vector3()),d=camera.position.distanceTo(w);if(d>mesh.userData.interact.range)continue;w.sub(camera.position).normalize();if(forward.dot(w)<.25)continue;if(d<bd){best=mesh;bd=d;}}return best;}
function interact(){const t=nearestInteractable();if(t)t.userData.interact.action();}
window.addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='KeyE')interact();if(e.code==='Escape')controls.unlock();});window.addEventListener('keyup',e=>keys.delete(e.code));renderer.domElement.addEventListener('click',()=>{if(!controls.isLocked)controls.lock();});startEl.addEventListener('click',()=>{controls.lock();startEl.style.display='none';});controls.addEventListener('lock',()=>startEl.style.display='none');controls.addEventListener('unlock',()=>{if(elapsed<2)startEl.style.display='grid';});
function updatePlayer(dt){if(!controls.isLocked)return;let f=0,s=0;if(keys.has('KeyW'))f++;if(keys.has('KeyS'))f--;if(keys.has('KeyD'))s++;if(keys.has('KeyA'))s--;if(!f&&!s)return;const len=Math.hypot(f,s)||1,speed=keys.has('ShiftLeft')||keys.has('ShiftRight')?6.2:3.8;movePlayer(s/len*speed*dt,f/len*speed*dt);}
function minutesToClock(total){const m=Math.floor(total)%1440;return `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;}function updateClock(dt){gameMinutes+=dt*.5;clockEl.textContent=minutesToClock(gameMinutes);}
function updateTrain(dt){if(!train&&trainIndex<trainSchedule.length&&gameMinutes>=trainSchedule[trainIndex]){addTrain();trainIndex++;}if(!train)return;train.group.position.z+=train.speed*dt;if(train.group.position.z>20){scene.remove(train.group);train=null;signalClear=false;signalDisc.material=M.red;signalLamp.color.setHex(0xb52c2c);leverPivot.rotation.z=0;barrierPivot.userData.target=0;objectiveEl.textContent=dinnerPacked?'Train passed. Return to your signal post.':'Train passed. Quiet gap — prepare your dinner at the stove.';}}
function updateDoor(dt){doorPivot.rotation.y=THREE.MathUtils.damp(doorPivot.rotation.y,doorPivot.userData.target??0,7,dt);}function updateBarrier(dt){barrierPivot.rotation.z=THREE.MathUtils.damp(barrierPivot.rotation.z,barrierPivot.userData.target??0,6,dt);}function updateLamp(dt){lampTime+=dt;const c=lampTime%5.5;let i=5.5;if(c>3.65&&c<3.82)i=.25;if(c>3.95&&c<4.08)i=.8;if(c>4.14&&c<4.24)i=.15;if(c>4.34&&c<4.42)i=4.5;streetLamp.intensity=i;}function updateUI(){const t=nearestInteractable();interactionEl.textContent=t?`E · ${t.userData.interact.label}`:'';interactionEl.style.opacity=t?'1':'0';hintEl.textContent=controls.isLocked?'WASD move · Mouse look · E interact · Shift sprint · Esc release mouse':'Click the scene to start · WASD move · Mouse look · E interact · Shift sprint';}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);elapsed+=dt;updatePlayer(dt);updateClock(dt);updateTrain(dt);updateDoor(dt);updateBarrier(dt);updateLamp(dt);updateUI();renderer.render(scene,camera);}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
